FROM ubuntu:20.04

ENV NUMBER_VERSION=21.0
ENV NAME_VERSION=sidney
ENV SEMANTIC_VERSION=10.4.0

RUN apt-get -y update \
    && apt-get -y install \
    vim \
    wget \
    curl \
    unzip \
    build-essential \
    zlib1g-dev \
    libcurl4-gnutls-dev \
    xterm \
    && apt-get -y autoremove \
    && apt-get -y autoclean
RUN wget https://github.com/Valdeirsk8/docker-dev-delphi/releases/download/${SEMANTIC_VERSION}-${NAME_VERSION}/PAServer_${NUMBER_VERSION}.tar.gz \
    && tar -xzvf PAServer_$NUMBER_VERSION.tar.gz \
    && rm PAServer_$NUMBER_VERSION.tar.gz

WORKDIR /PAServer-$NUMBER_VERSION

EXPOSE 64211
EXPOSE 9000

CMD ["./paserver", "-password="]